version: "3.7"
services:
  app:
    build:
      args:
        user: servicourrier
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: servicourrier
    container_name: servicourrier-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - servicourrier

  db:
    image: mysql:5.7
    container_name: servicourrier-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      servicourrier:
        ipv4_address: 10.5.0.5

  nginx:
    image: nginx:alpine
    container_name: servicourrier-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - servicourrier

networks:
  servicourrier:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1