
const welcome = "¡BIENVENIDO A LA SOLUCIÓN PARA TU LOGÍSTICA!";
const title = "PROPUESTA DE SERVICIO";
const mainText = "BRINDAMOS UN SERVICIO DE ALTA CALIDAD A NUESTROS CLIENTES Y ALIADOS ESTRATÉGICOS A TRAVÉS DE UNA SOLUCIÓN CONFIABLE Y RESPONSABLE EN EL MANEJO DE SUS DOCUMENTOS, MERCANCÍAS Y TRÁMITES";

export { welcome, title, mainText };