const EstadoServiciosEnum = Object.freeze({
    SERVICIOS_INCIADO: 1,
    SERVICIO_DIRECCION_CONFIRMADA: 2,
    SERVICIO_USUARIOS_ASIGNADOS: 3,
    SERVICIO_CON_DETALLE: 4,
    SERVICIO_PENDIENTE: 5,
    SERVICIO_APROBADO: 6,
    SERVICIO_RECHAZADO: 7,
    SERVICIO_EN_PROCESO: 8,
    SERVICIO_APLAZADO: 9,
    SERVICIO_REALIZADO: 10,
    SERVICIO_ENTREGADO: 11,
});

export default EstadoServiciosEnum;
